apiVersion: v1
kind: Service
metadata:
  name: cdr-api
  namespace: cdr-system

spec:
  selector:
    app: cdr

  type: ClusterIP

  ports:
  - name: cdr-api
    port: 3000
    targetPort: cdr-api
  - name: cdr-debug
    port: 4000
