apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base/cdr/
patches:
- path: ./dev-cdr-patch-deploy.yaml
images:
- name: service-image
  newName: amplypower/service/cdr-api
  newTag: 0.0.1
