apiVersion: v1
kind: Namespace
metadata:
  name: cdr-system

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cdr
  namespace: cdr-system

spec:
  selector:
    matchLabels:
      app: cdr

  template:
    metadata:
      labels:
        app: cdr

    spec:
      terminationGracePeriodSeconds: 60

      containers:
      - name: cdr-api
        image: service-image

        env:
        - name: GOMAXPROCS
          valueFrom:
            resourceFieldRef:
              resource: limits.cpu
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: KUBERNETES_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: KUBERNETES_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: KUBERNETES_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName

        ports:  
        - name: cdr-api
          containerPort: 3000
        - name: cdr-debug
          containerPort: 4000

        readinessProbe: # readiness probes mark the service available to accept traffic.
          httpGet:
            path: /readiness
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 2

        livenessProbe: # liveness probes mark the service alive or dead (to be restarted).
          httpGet:
            path: /liveness
            port: 3000
          initialDelaySeconds: 2
          periodSeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 2

---

apiVersion: v1
kind: Service
metadata:
  name: cdr-api
  namespace: cdr-system
  