apiVersion: v1
kind: Namespace
metadata:
  name: cdr-system

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cdr
  namespace: cdr-system

spec:
  selector:
    matchLabels:
      app: cdr

  template:
    metadata:
      labels:
        app: cdr

    spec:
      terminationGracePeriodSeconds: 60

      containers:
      - name: cdr-api
        image: service-image

        env:
        - name: GOMAXPROCS
          valueFrom:
            resourceFieldRef:
              resource: limits.cpu

        ports:  
        - name: cdr-api
          containerPort: 3000
        - name: cdr-debug
          containerPort: 4000

---

apiVersion: v1
kind: Service
metadata:
  name: cdr-api
  namespace: cdr-system
  